JOYNAPP/join2

- client/components/SignupNew.js
- client/components/index.js
- client/routes.js
- client/store/user.js
> Feature added: Sign up with name, email, and password

- server/db/models/contract.js
- server/db/models/index.js
> Feature Added: User and Contract updated models

- script/seed.js
> Feature Added: Seed File

- server/db/models/contract.js
- server/db/models/index.js
- server/db/models/userContract.js
> (Backend): Model Adjustments and created associations

- public/index.html
- public/style.css
> Feature Added: Splash Screen

- script/seed.js
Adds some some demo data + pre-associated concerts.
> seed associations

- server/db/models/user.js
> Model Updates: Allowing Signup without Credit Card Info

- client/components/FriendList.js
- client/components/SingleEvent.js
- client/store/contract.js
- client/store/index.js
- server/api/contracts.js
- server/api/index.js
> Contract join table

- client/components/inbox.js
> Feature: Inbox Component with Confirm and Decline buttons

- client/components/FriendList.js
- client/components/SingleEvent.js
- public/index.html
- public/style.css
- public/style.scss
- server/api/contracts.js
> Single event

- client/app.js
- client/components/FriendList.js
- client/components/inbox.js
- client/routes.js
- public/style.css
- script/seed.js
- server/api/userContract.js
- server/db/models/index.js
-This feature is still a bit buggy, but if a user is logged in then the inbox view will pull the contracts that they are associated with and map over them to load each contract with an "Accept" and "Decline" button
-The contracts do NOT currently pull the associated event information
---
> Feature Updated: Inbox View Can Pull User's Contracts If User Logged in

- client/app.js
- client/components/FriendList.js
- client/components/inbox.js
- client/routes.js
- client/store/contract.js
- public/style.css
- script/seed.js
- server/api/userContract.js
- server/db/models/index.js
Users can now accept or decline an event and it will change in the database! This uses a thunk in the contract store. 
---
> Respond contracts

- server/api/userContract.js
> Bug Fix: User Commits or Declines Event

- client/components/all-events.js
- client/routes.js
> click on name to go to single event

- client/components/FriendList.js
- client/components/SingleEvent.js
- client/store/user.js
- server/api/users.js
> Feature Update: Bug fixes in single event page

- client/components/FriendList.js
- client/components/SingleEvent.js
> Feature Update: Single Page Doesnt Show Current User AS Friend Option

- client/components/inbox.js
- client/store/contract.js
> Feature Update: Inbox View Lists All Users Events + Bug Fix

- client/components/inbox.js
- client/store/contract.js
- server/api/userContract.js
> Feature Added: Contract Fulfillment Works

- client/components/inbox.js
> Feature Update: Inbox View - Event Info Button Takes User To Correct URL

- client/components/FriendList.js
- package-lock.json
- package.json
- webpack.config.js
> Feature Added: Toast Notification Upon Invite

- client/components/inbox.js
> Feature Added: Toast Notifications for Confirm and Decline Buttons

- client/components/inbox.js
- client/store/contract.js
- server/api/contracts.js
> Feature Added: User Can See Friends Who Are Also Invited To Their Events

- client/components/SingleEvent.js
- client/components/inbox.js
- client/store/event.js
- client/store/index.js
- public/style.css
- script/seed.js
> Small Changes: Added Events To Seed, Small Changes On Single Event Page

- client/components/inbox.js
- client/components/navbar.js
- public/style.css
> (Frontend): Logo and Navbar Styling

- public/style.css
- server/api/logic.js
> adding a font

- client/components/inbox.js
- client/components/navbar.js
- client/store/contract.js
> Inbox view

- client/components/all-events.js
- server/api/events.js
> Eb api front end

- client/components/navbar.js
- public/index.html
- public/style.css
> Edit Navbar and Logo

- client/components/all-events.js
- public/index.html
- public/style.css
> Events Styling

- client/components/SingleEvent.js
- client/components/all-events.js
> feat(single-event): pull eventId from url and render event details

- client/components/FriendList.js
- client/components/SingleEvent.js
- client/components/inbox.js
- client/components/navbar.js
- client/components/user-home.js
- client/store/user.js
- public/style.css
- server/api/contracts.js
- server/db/models/contract.js
> Updates: Lots Of Updates To Inbox, Contract Model, and Styling

- client/components/inbox.js
- client/components/navbar.js
Fixes name of of user with only email (google login) to show email instead of nothing on navbar and event inbox component
> fixes naming bug

- client/components/all-events.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- public/style.css
> Feature Update: Welcome Message

- client/components/all-events.js
- client/components/inbox.js
- public/index.html
> Bug Fix: Event Info Goes To Correct Single Event

- client/components/inbox.js
> Feature Update: Inbox View Shows User Responses

- client/components/all-events.js
- public/style.css
> Events in Columns

- client/components/FriendList.js
- client/components/all-events.js
- client/components/inbox.js
- client/components/navbar.js
- public/style.css
> Styling Changes To Inbox And Font Colors

- client/components/all-events.js
- public/style.css
> Edited event list grid

- client/components/SignupNew.js
- client/components/SingleEvent.js
- client/components/all-events.js
- client/components/auth-form.js
- client/components/inbox.js
- client/components/navbar.js
- public/index.html
- public/style.css
> color change!

- client/components/SingleEvent.js
- public/style.css
> Edited Single Event with Description Styling

- client/components/inbox.js
- script/seed.js
- server/db/models/event.js
- server/db/models/index.js
> Feature Update: New Seed File
